server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: sheeesh
  accessToken:
    lifetime: 1h
  refreshToken:
    lifetime: 1d

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: wishlist-service
  datasource:
    url: jdbc:postgresql://localhost:5432/wishlist
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
      enabled: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: book-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        max.partition.fetch.bytes: 10485760 # 10 MB
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        max.request.size: 10485760 # 10 MB
